version: '3.7'

services:
  rpc-api:
    build: .
    environment:
      - RMQ_URLS=["amqp://guest:guest@host.docker.internal:5672/eth"]
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - 5000:5000
      - 18332
      - 8332
